import Link from 'next/link'

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="flex gap-2">
          <Link href="/">홈</Link>
          <Link href="/about">어바웃</Link>
          <Link href="/pf">포트폴리오</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
