import Link from "next/link";

import "./globals.css";

import localFont from "next/font/local";

const pretendard = localFont({
  src: "./../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <div className="flex gap-2">
          <Link href="/">홈</Link>
          <Link href="/about">어바웃</Link>
          <Link href="/pf">포트폴리오</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
